### ISSUE TITLE
[FEATURE REQUEST] Automatically unzip + place in appropriate locations + Add to config.plist

### ISSUE THREAD

**Issue by khrj** [shreyas1307/hackintosh-pkg-cli#6]
Hi 👋
This is a nice tool to download zips, yet it does only that - Downloads zips.
It would be great if it's possible to unzip OpenCorePkg, put kexts in OC/kexts, and add their entries to config.plist

**Comment by shreyas1307** [comment]
Hello,  Thanks for leaving feedback. 

This tool cuts out the usually frustrating bit of navigating manually to the releases/downloads folder of a GitHub/Bitbucket repo and downloading the files. 

There are tools already developed, where you can open it, make a snapshot of your folder it auto-adds those kexts as entries into your config.plist [ProperTree](https://github.com/corpnewt/ProperTree) Also due to the constantly evolving nature of OpenCore, it'll be more complex to maintain. 

Cheers.

**Comment by khrj** [comment]
Hi 👋,

I'm aware of ProperTree, however that only adds entries to config.plist

I don't see why hackintosh-pkg-cli couldn't unzip OpenCorePkg, and place kexts in the kexts folder after unzipping

Thanks!
